var listedOBj = {};
var disp = getDisp();
for (var key in disp) {
  if (disp[key]["listeditem"] == "Y") {
    listedOBj[key] = disp[key];
  }
}
var cols = [];

for (var key in listedOBj) {
  var col = {};

  col.header = listedOBj[key].displayname;
  col.accessor = d => d[listedOBj[key].fieldname].fieldvalue;
  col.id = listedOBj[key].fieldname;

  cols.push(col);
}

function getData() {
  return [
    {
      
      "createdby_val": {
      "fieldvalue": "5"
      },
      "documentgrouplink": {
      "fieldvalue": "2"
      },
      "rlc16": {
      "tooltip": "Enter the applicants tribe status",
      "fieldname": "rlc16",
      "displayname": "Tribe Status",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 96
      },
      "createddatedt": {
      "fieldvalue": "20120718000000"
      },
      "datefield1dt": {
      "fieldvalue": " "
      },
      "xallowed": {
      "fieldvalue": "N"
      },
      "determinationdatedt": {
      "fieldvalue": " "
      },
      "documentgroup_val": {
      "fieldvalue": "2"
      },
      "createdby": {
      "tooltip": "Pick the applicant name from the list",
      "linkTo": {
      "link": {
      "fieldvalue": "5"
      },
      "lsubtype": "applicant",
      "ltype": "ci"
      },
      "fieldname": "createdby",
      "isLinkType": true,
      "linkToType": "tabNavigate",
      "displayname": "Individual Applicant",
      "fieldvalue": "Teton, Elese",
      "sortposition": 0,
      "fieldtype": "lookup",
      "sortorder": 30
      },
      "flexfield8": {
      "tooltip": "Irrigation or land application method (check all that apply)",
      "fieldname": "flexfield8",
      "displayname": "Irrigation Method",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "checkbox",
      "sortorder": 250
      },
      "rlc11": {
      "fieldname": "rlc11",
      "displayname": "Zip Code",
      "fieldvalue": "83203",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 91
      },
      "commmanual": {
      "tooltip": "Method for monitoring the diversion.",
      "fieldname": "commmanual",
      "displayname": "Monitoring",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 230
      },
      "building": {
      "fieldname": "building",
      "displayname": "Nearest Source of Water",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "pickwindow",
      "sortorder": 280
      },
      "createdby_valdt": {
      "fieldvalue": "000000005"
      },
      "createdbylink": {
      "fieldvalue": "5"
      },
      "flexfield41": {
      "fieldname": "flexfield41",
      "displayname": "Class",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 16
      },
      "releasedate": {
      "tooltip": "Estimated well construction completion date ",
      "fieldname": "releasedate",
      "displayname": "Completion Date",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 320
      },
      "flexfield11": {
      "tooltip": "Enter the date when the applicant will begin using the water source",
      "fieldname": "flexfield11",
      "displayname": "Period of Use (Start)",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 190
      },
      "rlc5": {
      "tooltip": "Enter the phone number of the applicant",
      "fieldname": "rlc5",
      "displayname": "Phone Number",
      "fieldvalue": "208-239-4580",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 80
      },
      "description": {
      "tooltip": "Enter comments regarding water management including other monitoring, distribution, and irrigation methods",
      "fieldname": "description",
      "displayname": "Comments",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "textarea",
      "sortorder": 255
      },
      "flexfield18": {
      "tooltip": "Enter the applicants mailing address",
      "fieldname": "flexfield18",
      "displayname": "Mailing Address",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "readonly",
      "sortorder": 45
      },
      "releaseagency": {
      "tooltip": "What equipment will be used to apply water to your place of use?",
      "fieldname": "releaseagency",
      "displayname": "Distribution Method",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "checkbox",
      "sortorder": 240
      },
      "datefield2": {
      "fieldname": "datefield2",
      "displayname": "Date Completed",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 11
      },
      "documentnumberdt": {
      "fieldvalue": "000001009"
      },
      "flexfield15": {
      "tooltip": "If well is flowing artesian, describe your water control and conservation works.  Include pressure (psi), ft below ground, access port",
      "fieldname": "flexfield15",
      "displayname": "Artesian Flows",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "textarea",
      "sortorder": 350
      },
      "flexfield9dt": {
      "fieldvalue": "000000000"
      },
      "itemid": {
      "fieldname": "itemid",
      "displayname": "Tribal Ground Water Use Permit Application",
      "fieldvalue": "49480",
      "sortposition": 0,
      "fieldtype": "itemid",
      "sortorder": 0
      },
      "shelf": {
      "tooltip": "Check the appropriate box to mark consumptive (Y) or non-conumptive (N)",
      "fieldname": "shelf",
      "displayname": "Annual Diversion Rate",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "checkbox",
      "sortorder": 185
      },
      "flexfield40": {
      "fieldname": "flexfield40",
      "displayname": "Type",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 15
      },
      "flexfield1": {
      "tooltip": "Enter the address of the well builder",
      "fieldname": "flexfield1",
      "displayname": "Address",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "text",
      "sortorder": 310
      },
      "createddate": {
      "tooltip": "Enter the date of application",
      "fieldname": "createddate",
      "displayname": "Application Date",
      "fieldvalue": "18-JUL-2012",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 8
      },
      "building_val": {
      "fieldvalue": ""
      },
      "status": {
      "tooltip": "Enter the status of the application",
      "fieldname": "status",
      "displayname": "Status",
      "fieldvalue": "In Process",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 20
      },
      "determinationdate": {
      "tooltip": "Enter the date when the applicant will end using the water source",
      "fieldname": "determinationdate",
      "displayname": "Period of Use (End)",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 200
      },
      "rlc10": {
      "fieldname": "rlc10",
      "displayname": "State",
      "fieldvalue": "ID",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 90
      },
      "flexfield6linkdt": {
      "fieldvalue": "000000000"
      },
      "flexfield6": {
      "tooltip": "Enter the lease number",
      "fieldname": "flexfield6",
      "displayname": "Lease No.",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "pickwindow",
      "sortorder": 145
      },
      "createdbylinkdt": {
      "fieldvalue": "000000005"
      },
      "datefield3dt": {
      "fieldvalue": " "
      },
      "rlc3": {
      "fieldname": "rlc3",
      "displayname": "State 2",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 73
      },
      "flexfield2": {
      "fieldname": "flexfield2",
      "displayname": "Co-Applicant",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "pickwindow",
      "sortorder": 40
      },
      "flexfield43": {
      "fieldname": "flexfield43",
      "displayname": "Land Ownership",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 19
      },
      "rlc6": {
      "tooltip": "Enter the email of the applicant",
      "fieldname": "rlc6",
      "displayname": "Email",
      "fieldvalue": "eteton@sbtribes.com",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 84
      },
      "flexfield3": {
      "tooltip": "Amount of water proposed to be used from each source in cubic-feet-per-second(cfs)",
      "fieldname": "flexfield3",
      "displayname": "Max Flow Rate",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "text",
      "sortorder": 180
      },
      "flexfield13": {
      "tooltip": "Description of well development:  No., Diameter, Casing size, Perforation interval, Seal depth, Depth to water, Total depth, filter pack, drill method",
      "fieldname": "flexfield13",
      "displayname": "Well Description",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "textarea",
      "sortorder": 340
      },
      "rlc14": {
      "fieldname": "rlc14",
      "displayname": "Fax Number",
      "fieldvalue": "(208) 239-4580",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 94
      },
      "rlc19": {
      "fieldname": "rlc19",
      "displayname": "Lease Type",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 155
      },
      "datefield1": {
      "fieldname": "datefield1",
      "displayname": "Date Received",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 9
      },
      "rlc1": {
      "fieldname": "rlc1",
      "displayname": "Mailing Address 2",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 71
      },
      "flexfield6_val": {
      "fieldvalue": ""
      },
      "rlc9": {
      "fieldname": "rlc9",
      "displayname": "City",
      "fieldvalue": "Ft. Hall",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 89
      },
      "rlc2": {
      "fieldname": "rlc2",
      "displayname": "City 2",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 72
      },
      "datefield3": {
      "fieldname": "datefield3",
      "displayname": "Expiration Date",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "date",
      "sortorder": 12
      },
      "documentnumber": {
      "fieldname": "documentnumber",
      "displayname": "Application Number",
      "fieldvalue": "1009",
      "sortposition": 0,
      "fieldtype": "autonumber",
      "sortorder": 2
      },
      "documentgroup": {
      "tooltip": "Name of company, firm, partnership, cooperative, municipal or organization applying for water",
      "linkTo": {
      "link": {
      "fieldvalue": "2"
      },
      "lsubtype": null,
      "ltype": "organization"
      },
      "fieldname": "documentgroup",
      "isLinkType": true,
      "linkToType": "tabNavigate",
      "displayname": "Name of Organization",
      "fieldvalue": "TRIBE",
      "sortposition": 0,
      "fieldtype": "pickwindow",
      "sortorder": 86
      },
      "flexfield5": {
      "tooltip": "Enter the name of the company or individual that will construct the well",
      "fieldname": "flexfield5",
      "displayname": "Well Contructed by",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "text",
      "sortorder": 300
      },
      "flexfield4": {
      "tooltip": "Enter the distance from the well to the nearest stream or lake.",
      "fieldname": "flexfield4",
      "displayname": "Well Distance",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "text",
      "sortorder": 290
      },
      "flexfield2_val": {
      "fieldvalue": ""
      },
      "flexfield11dt": {
      "fieldvalue": " "
      },
      "rlc11dt": {
      "fieldvalue": "000083203"
      },
      "xcontrolled": {
      "fieldvalue": "N"
      },
      "documentgrouplinkdt": {
      "fieldvalue": "000000002"
      },
      "flexfield20": {
      "tooltip": "Enter the zip code of the mailing address",
      "fieldname": "flexfield20",
      "displayname": "Zip",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "readonly",
      "sortorder": 70
      },
      "rlc4": {
      "fieldname": "rlc4",
      "displayname": "Zip 2",
      "fieldvalue": "572",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 74
      },
      "flexfield9": {
      "tooltip": "Enter the number of well(s)",
      "fieldname": "flexfield9",
      "displayname": "Number of well(s)",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "text",
      "sortorder": 270
      },
      "rlc15": {
      "fieldname": "rlc15",
      "displayname": "Email Address",
      "fieldvalue": "Shoshone Bannock Tribes",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 95
      },
      "rlc8": {
      "fieldname": "rlc8",
      "displayname": "Title of Representive",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 87
      },
      "releasedatedt": {
      "fieldvalue": " "
      },
      "flexfield19": {
      "tooltip": "Enter the state of the mailing address",
      "fieldname": "flexfield19",
      "displayname": "State",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "readonly",
      "sortorder": 60
      },
      "flexfield6link": {
      "fieldvalue": ""
      },
      "rlc18": {
      "tooltip": "Term of lease in years",
      "fieldname": "rlc18",
      "displayname": "Term of Lease",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 150
      },
      "numofpages": {
      "tooltip": "Select the applicable purpose of use",
      "fieldname": "numofpages",
      "displayname": "Purpose of Use",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 170
      },
      "flexfield42": {
      "fieldname": "flexfield42",
      "displayname": "Fee Paid",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "picklist",
      "sortorder": 18
      },
      "rlc13": {
      "fieldname": "rlc13",
      "displayname": "Mobile Phone Number",
      "fieldvalue": "(208) 239-4580",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 93
      },
      "itemiddt": {
      "fieldvalue": "000049480"
      },
      "datefield2dt": {
      "fieldvalue": " "
      },
      "rlc7": {
      "tooltip": "Person respresenting the organization",
      "fieldname": "rlc7",
      "displayname": "Name of Representative",
      "fieldvalue": "Elese D. Teton",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 87
      },
      "rlc12": {
      "fieldname": "rlc12",
      "displayname": "Phone Number Day and Night",
      "fieldvalue": "(123)  123-1232",
      "sortposition": 0,
      "fieldtype": "linkedfield",
      "sortorder": 92
      },
      "flexfield37": {
      "tooltip": "Enter the city of the mailing address",
      "fieldname": "flexfield37",
      "displayname": "City",
      "fieldvalue": "",
      "sortposition": 0,
      "fieldtype": "readonly",
      "sortorder": 50
      }
      }
  ]
}

console.log(listedOBj);
console.log(cols);
function getDisp() {
  return {
    "itemid": {
    "fieldname": "itemid",
    "itemtypecd": "document",
    "displayname": "Tribal Ground Water Use Permit Application",
    "fieldlength": 0,
    "maxlength": 0,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "itemid",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 0,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "documentnumber": {
    "fieldname": "documentnumber",
    "itemtypecd": "document",
    "displayname": "Application Number",
    "fieldlength": 50,
    "maxlength": 50,
    "required": "Y",
    "listeditem": "Y",
    "fieldtype": "autonumber",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": "1000",
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 2,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "createddate": {
    "fieldname": "createddate",
    "itemtypecd": "document",
    "displayname": "Application Date",
    "fieldlength": 12,
    "maxlength": 12,
    "required": "Y",
    "listeditem": "Y",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the date of application",
    "keyfield": "Y",
    "sortorder": 8,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "datefield1": {
    "fieldname": "datefield1",
    "itemtypecd": "document",
    "displayname": "Date Received",
    "fieldlength": 8,
    "maxlength": 8,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 9,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "datefield2": {
    "fieldname": "datefield2",
    "itemtypecd": "document",
    "displayname": "Date Completed",
    "fieldlength": 8,
    "maxlength": 8,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 11,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "datefield3": {
    "fieldname": "datefield3",
    "itemtypecd": "document",
    "displayname": "Expiration Date",
    "fieldlength": 8,
    "maxlength": 8,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 12,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "flexfield40": {
    "fieldname": "flexfield40",
    "itemtypecd": "document",
    "displayname": "Type",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "GWTypes",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 15,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "flexfield41": {
    "fieldname": "flexfield41",
    "itemtypecd": "document",
    "displayname": "Class",
    "fieldlength": 5,
    "maxlength": 5,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "GWClass",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 16,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "flexfield42": {
    "fieldname": "flexfield42",
    "itemtypecd": "document",
    "displayname": "Fee Paid",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "YesNo",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 18,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "flexfield43": {
    "fieldname": "flexfield43",
    "itemtypecd": "document",
    "displayname": "Land Ownership",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "GWLandOwnership",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 19,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "status": {
    "fieldname": "status",
    "itemtypecd": "document",
    "displayname": "Status",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "Y",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "approval",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the status of the application",
    "keyfield": "Y",
    "sortorder": 20,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": null
    },
    "rlc0": {
    "fieldname": "rlc0",
    "itemtypecd": "document",
    "displayname": "Applicant Information",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "label",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter Application Information",
    "keyfield": "N",
    "sortorder": 25,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": null,
    "lc": null
    },
    "createdby": {
    "fieldname": "createdby",
    "itemtypecd": "document",
    "displayname": "Individual Applicant",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "Y",
    "listeditem": "Y",
    "fieldtype": "lookup",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "ci_properties",
    "parentcolumn": "flexfield27",
    "parentfieldname": "itemid",
    "parentsubtype": "applicant",
    "defaultvalue": "Request.Params.Get(\"defaultrelid\")",
    "linkfield": "itemid",
    "linktype": "drilldown",
    "tooltip": "Pick the applicant name from the list",
    "keyfield": "Y",
    "sortorder": 30,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": "_11"
    },
    "flexfield2": {
    "fieldname": "flexfield2",
    "itemtypecd": "document",
    "displayname": "Co-Applicant",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "pickwindow",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "lastnamefirst",
    "parentfieldname": "itemid",
    "parentsubtype": "contact",
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 40,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": "_12"
    },
    "flexfield18": {
    "fieldname": "flexfield18",
    "itemtypecd": "document",
    "displayname": "Mailing Address",
    "fieldlength": 60,
    "maxlength": 250,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "readonly",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the applicants mailing address",
    "keyfield": "N",
    "sortorder": 45,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield37": {
    "fieldname": "flexfield37",
    "itemtypecd": "document",
    "displayname": "City",
    "fieldlength": 60,
    "maxlength": 250,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "readonly",
    "itemvaluegroup": "city",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the city of the mailing address",
    "keyfield": "N",
    "sortorder": 50,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield19": {
    "fieldname": "flexfield19",
    "itemtypecd": "document",
    "displayname": "State",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "readonly",
    "itemvaluegroup": "state",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the state of the mailing address",
    "keyfield": "N",
    "sortorder": 60,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield20": {
    "fieldname": "flexfield20",
    "itemtypecd": "document",
    "displayname": "Zip",
    "fieldlength": 10,
    "maxlength": 50,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "readonly",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the zip code of the mailing address",
    "keyfield": "N",
    "sortorder": 70,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc1": {
    "fieldname": "rlc1",
    "itemtypecd": "document",
    "displayname": "Mailing Address 2",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "companyname",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 71,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc2": {
    "fieldname": "rlc2",
    "itemtypecd": "document",
    "displayname": "City 2",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "flexfield4",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 72,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc3": {
    "fieldname": "rlc3",
    "itemtypecd": "document",
    "displayname": "State 2",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "country",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 73,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc4": {
    "fieldname": "rlc4",
    "itemtypecd": "document",
    "displayname": "Zip 2",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "flexfield5",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 74,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc5": {
    "fieldname": "rlc5",
    "itemtypecd": "document",
    "displayname": "Phone Number",
    "fieldlength": 30,
    "maxlength": 30,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "phonenumber",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the phone number of the applicant",
    "keyfield": "N",
    "sortorder": 80,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc6": {
    "fieldname": "rlc6",
    "itemtypecd": "document",
    "displayname": "Email",
    "fieldlength": 40,
    "maxlength": 40,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "email",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the email of the applicant",
    "keyfield": "N",
    "sortorder": 84,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "documentgroup": {
    "fieldname": "documentgroup",
    "itemtypecd": "document",
    "displayname": "Name of Organization",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "pickwindow",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "organizationname",
    "parentfieldname": "itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": "itemid",
    "linktype": "drilldown",
    "tooltip": "Name of company, firm, partnership, cooperative, municipal or organization applying for water",
    "keyfield": "Y",
    "sortorder": 86,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": "_23"
    },
    "rlc7": {
    "fieldname": "rlc7",
    "itemtypecd": "document",
    "displayname": "Name of Representative",
    "fieldlength": 50,
    "maxlength": 50,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "cmd",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Person respresenting the organization",
    "keyfield": "Y",
    "sortorder": 87,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc8": {
    "fieldname": "rlc8",
    "itemtypecd": "document",
    "displayname": "Title of Representive",
    "fieldlength": 50,
    "maxlength": 50,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "flexfield1",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 87,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc9": {
    "fieldname": "rlc9",
    "itemtypecd": "document",
    "displayname": "City",
    "fieldlength": 40,
    "maxlength": 40,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "flexfield2",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 89,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc10": {
    "fieldname": "rlc10",
    "itemtypecd": "document",
    "displayname": "State",
    "fieldlength": 40,
    "maxlength": 40,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "state",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 90,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc11": {
    "fieldname": "rlc11",
    "itemtypecd": "document",
    "displayname": "Zip Code",
    "fieldlength": 30,
    "maxlength": 30,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "modelid",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 91,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc12": {
    "fieldname": "rlc12",
    "itemtypecd": "document",
    "displayname": "Phone Number Day and Night",
    "fieldlength": 50,
    "maxlength": 50,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "mission",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 92,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc13": {
    "fieldname": "rlc13",
    "itemtypecd": "document",
    "displayname": "Mobile Phone Number",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "flexfield3",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 93,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc14": {
    "fieldname": "rlc14",
    "itemtypecd": "document",
    "displayname": "Fax Number",
    "fieldlength": 40,
    "maxlength": 40,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "subcmd",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 94,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc15": {
    "fieldname": "rlc15",
    "itemtypecd": "document",
    "displayname": "Email Address",
    "fieldlength": 40,
    "maxlength": 40,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "organization_properties",
    "parentcolumn": "vision",
    "parentfieldname": "documentgroup.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "Y",
    "sortorder": 95,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc16": {
    "fieldname": "rlc16",
    "itemtypecd": "document",
    "displayname": "Tribe Status",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": "tribestat",
    "subtypecd": "gwpermit",
    "parenttable": "user_properties",
    "parentcolumn": "securityofficername",
    "parentfieldname": "createdby.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the applicants tribe status",
    "keyfield": "N",
    "sortorder": 96,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc17": {
    "fieldname": "rlc17",
    "itemtypecd": "document",
    "displayname": "Place of Use (See Related Allotments for POU)",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "label",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Place of Use Information (See Related Allotments for POU)",
    "keyfield": "N",
    "sortorder": 120,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": null,
    "lc": null
    },
    "flexfield6": {
    "fieldname": "flexfield6",
    "itemtypecd": "document",
    "displayname": "Lease No.",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "pickwindow",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "document_properties",
    "parentcolumn": "documentnumber",
    "parentfieldname": "itemid",
    "parentsubtype": "lease",
    "defaultvalue": null,
    "linkfield": "itemid",
    "linktype": "drilldown",
    "tooltip": "Enter the lease number",
    "keyfield": "N",
    "sortorder": 145,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": "_35"
    },
    "rlc18": {
    "fieldname": "rlc18",
    "itemtypecd": "document",
    "displayname": "Term of Lease",
    "fieldlength": 5,
    "maxlength": 5,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "document_properties leasetable",
    "parentcolumn": "flexfield10",
    "parentfieldname": "flexfield6.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Term of lease in years",
    "keyfield": "N",
    "sortorder": 150,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc19": {
    "fieldname": "rlc19",
    "itemtypecd": "document",
    "displayname": "Lease Type",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "linkedfield",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "document_properties lease",
    "parentcolumn": "classification",
    "parentfieldname": "flexfield6.itemid",
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 155,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc20": {
    "fieldname": "rlc20",
    "itemtypecd": "document",
    "displayname": "Water Use (See Relations Tab for water sources)",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "label",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Water Use (See Relations Tab for water sources)",
    "keyfield": "N",
    "sortorder": 160,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": null,
    "lc": null
    },
    "numofpages": {
    "fieldname": "numofpages",
    "itemtypecd": "document",
    "displayname": "Purpose of Use",
    "fieldlength": 5,
    "maxlength": 5,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "picklist",
    "itemvaluegroup": "permitpurpose",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Select the applicable purpose of use",
    "keyfield": "N",
    "sortorder": 170,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield3": {
    "fieldname": "flexfield3",
    "itemtypecd": "document",
    "displayname": "Max Flow Rate",
    "fieldlength": 60,
    "maxlength": 250,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "text",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Amount of water proposed to be used from each source in cubic-feet-per-second(cfs)",
    "keyfield": "N",
    "sortorder": 180,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "shelf": {
    "fieldname": "shelf",
    "itemtypecd": "document",
    "displayname": "Annual Diversion Rate",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "Y",
    "fieldtype": "checkbox",
    "itemvaluegroup": "YesNo",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Check the appropriate box to mark consumptive (Y) or non-conumptive (N)",
    "keyfield": "N",
    "sortorder": 185,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield11": {
    "fieldname": "flexfield11",
    "itemtypecd": "document",
    "displayname": "Period of Use (Start)",
    "fieldlength": 7,
    "maxlength": 7,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the date when the applicant will begin using the water source",
    "keyfield": "N",
    "sortorder": 190,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "determinationdate": {
    "fieldname": "determinationdate",
    "itemtypecd": "document",
    "displayname": "Period of Use (End)",
    "fieldlength": 7,
    "maxlength": 7,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the date when the applicant will end using the water source",
    "keyfield": "N",
    "sortorder": 200,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "rlc21": {
    "fieldname": "rlc21",
    "itemtypecd": "document",
    "displayname": "Related PODs",
    "fieldlength": 1,
    "maxlength": 1,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "label",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Related PODs",
    "keyfield": "N",
    "sortorder": 220,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": "Y",
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": null,
    "lc": null
    },
    "commmanual": {
    "fieldname": "commmanual",
    "itemtypecd": "document",
    "displayname": "Monitoring",
    "fieldlength": 2,
    "maxlength": 2,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "picklist",
    "itemvaluegroup": "monitortype",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Method for monitoring the diversion.",
    "keyfield": "N",
    "sortorder": 230,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "releaseagency": {
    "fieldname": "releaseagency",
    "itemtypecd": "document",
    "displayname": "Distribution Method",
    "fieldlength": 80,
    "maxlength": 80,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "checkbox",
    "itemvaluegroup": "distributiontype",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "What equipment will be used to apply water to your place of use?",
    "keyfield": "N",
    "sortorder": 240,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield8": {
    "fieldname": "flexfield8",
    "itemtypecd": "document",
    "displayname": "Irrigation Method",
    "fieldlength": 3,
    "maxlength": 3,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "checkbox",
    "itemvaluegroup": "applicationmethod",
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Irrigation or land application method (check all that apply)",
    "keyfield": "N",
    "sortorder": 250,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "description": {
    "fieldname": "description",
    "itemtypecd": "document",
    "displayname": "Comments",
    "fieldlength": 50,
    "maxlength": 2000,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "textarea",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter comments regarding water management including other monitoring, distribution, and irrigation methods",
    "keyfield": "N",
    "sortorder": 255,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield9": {
    "fieldname": "flexfield9",
    "itemtypecd": "document",
    "displayname": "Number of well(s)",
    "fieldlength": 10,
    "maxlength": 10,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "text",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the number of well(s)",
    "keyfield": "N",
    "sortorder": 270,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "building": {
    "fieldname": "building",
    "itemtypecd": "document",
    "displayname": "Nearest Source of Water",
    "fieldlength": 10,
    "maxlength": 10,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "pickwindow",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": "part_properties",
    "parentcolumn": "partno",
    "parentfieldname": "itemid",
    "parentsubtype": "watersource",
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": null,
    "keyfield": "N",
    "sortorder": 280,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar",
    "lc": "_50"
    },
    "flexfield4": {
    "fieldname": "flexfield4",
    "itemtypecd": "document",
    "displayname": "Well Distance",
    "fieldlength": 80,
    "maxlength": 250,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "text",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the distance from the well to the nearest stream or lake.",
    "keyfield": "N",
    "sortorder": 290,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield5": {
    "fieldname": "flexfield5",
    "itemtypecd": "document",
    "displayname": "Well Contructed by",
    "fieldlength": 80,
    "maxlength": 250,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "text",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the name of the company or individual that will construct the well",
    "keyfield": "N",
    "sortorder": 300,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield1": {
    "fieldname": "flexfield1",
    "itemtypecd": "document",
    "displayname": "Address",
    "fieldlength": 80,
    "maxlength": 250,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "text",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Enter the address of the well builder",
    "keyfield": "N",
    "sortorder": 310,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "releasedate": {
    "fieldname": "releasedate",
    "itemtypecd": "document",
    "displayname": "Completion Date",
    "fieldlength": 7,
    "maxlength": 7,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "date",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Estimated well construction completion date ",
    "keyfield": "N",
    "sortorder": 320,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield13": {
    "fieldname": "flexfield13",
    "itemtypecd": "document",
    "displayname": "Well Description",
    "fieldlength": 50,
    "maxlength": 4000,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "textarea",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "Description of well development:  No., Diameter, Casing size, Perforation interval, Seal depth, Depth to water, Total depth, filter pack, drill method",
    "keyfield": "N",
    "sortorder": 340,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    },
    "flexfield15": {
    "fieldname": "flexfield15",
    "itemtypecd": "document",
    "displayname": "Artesian Flows",
    "fieldlength": 50,
    "maxlength": 2000,
    "required": "N",
    "listeditem": "N",
    "fieldtype": "textarea",
    "itemvaluegroup": null,
    "subtypecd": "gwpermit",
    "parenttable": null,
    "parentcolumn": null,
    "parentfieldname": null,
    "parentsubtype": null,
    "defaultvalue": null,
    "linkfield": null,
    "linktype": null,
    "tooltip": "If well is flowing artesian, describe your water control and conservation works.  Include pressure (psi), ft below ground, access port",
    "keyfield": "N",
    "sortorder": 350,
    "sortposition": 0,
    "sortdirection": "asc",
    "childfieldname": null,
    "childxmldoc": null,
    "customsql": null,
    "exportcol": null,
    "importcol": null,
    "onblur": null,
    "onchange": null,
    "l": "rarar"
    }
    };
}


export {getData, getDisp};
