export const API = 'API';

export const REQUEST_ITEM_LIST = 'REQUEST_ITEM_LIST';
export const FETCH_ITEM_LIST_SUCCESS = 'FETCH_ITEM_LIST_SUCCESS';
export const FETCH_ITEM_LIST_ERROR = 'FETCH_ITEM_LIST_ERROR';
export const RECEIVE_ITEM_LIST = 'RECEIVE_ITEM_LIST';

export const REQUEST_ITEM_PROPETIES = 'REQUEST_ITEM_PROPETIES';
export const FETCH_ITEM_PROPETIES_SUCCESS = 'FETCH_ITEM_PROPETIES_SUCCESS';
export const FETCH_ITEM_PROPETIES_ERROR = 'FETCH_ITEM_PROPETIES_ERROR';
export const RECEIVE_ITEM_PROPETIES = 'RECEIVE_ITEM_PROPETIES';
export const RECEIVE_ITEM_PROPETIES_SECTIONS = 'RECEIVE_ITEM_PROPETIES_SECTIONS';
export const RECEIVE_ITEM_PROPETIES_TABS_BASEURL = 'RECEIVE_ITEM_PROPETIES_TABS_BASEURL';
export const TOGGLE_ITEMPROPERTIES_SECTION = "TOGGLE_ITEMPROPERTIES_SECTION";

export const REQUEST_ITEM_PROPETIES_BUTTONS = 'REQUEST_ITEM_PROPETIES_BUTTONS';
export const FETCH_ITEM_PROPETIES_BUTTONS_SUCCESS = 'FETCH_ITEM_PROPETIES_BUTTONS_SUCCESS';
export const FETCH_ITEM_PROPETIES_BUTTONS_ERROR = 'FETCH_ITEM_PROPETIES_BUTTONS_ERROR';
export const RECEIVE_ITEM_PROPETIES_BUTTONS = 'RECEIVE_ITEM_PROPETIES_BUTTONS';

export const REQUEST_ITEM_FORM_FIELDS= 'REQUEST_ITEM_FORM_FIELDS';
export const FETCH_ITEM_FORM_FIELDS_SUCCESS = 'FETCH_ITEM_FORM_FIELDS_SUCCESS';
export const FETCH_ITEM_FORM_FIELDS_ERROR = 'FETCHITEM_FORM_FIELDS_ERROR';
export const RECEIVE_ITEM_FORM_FIELDS = 'RECEIVE_ITEM_FORM_FIELDS';
export const RECEIVE_ITEM_FORM_FIELDS_SECTIONS = 'RECEIVE_ITEM_FORM_FIELDS_SECTIONS';
export const TOGGLE_ITEM_FORM_FIELDS_SECTION = "TOGGLEITEM_FORM_FIELDS_SECTION";
export const RECEIVE_ITEM_LIST_BUTTONS = 'RECEIVE_ITEM_LIST_BUTTONS';


export const ADD_TAB = "ADD_TAB";
export const UPDATE_TAB_URL = "UPDATE_TAB_URL";


export const START_NETWORK = 'START_NETWORK';
export const END_NETWORK = 'END_NETWORK';
